services:
  threadfin:
    image: fyb3roptik/threadfin:latest
    container_name: threadfin
    restart: unless-stopped
    network_mode: host
    environment:
      - THREADFIN_PORT=34400
    volumes:
      - ./config/threadfin:/home/threadfin/.threadfin

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=Atlantic/Reykjavik
    volumes:
      - ./config/plex:/config
      - /home/oli/media/tv:/data/tv
      - /home/oli/media/movies:/data/movies
      - /tmp/plex-transcode:/transcode
